import type { IssueStatus } from "./types";

export { type IssueStatus } from "./types";

export const issueStatuses: readonly IssueStatus[] = [
  "OPEN",
  "READY_FOR_DEV",
  "DEV_IN_PROGRESS",
  "DEV_REVIEW",
  "DEV_COMPLETED",
  "DEV_DEPLOYED",
  "QA_IN_PROGRESS",
  "QA_DEPLOYED",
  "READY_FOR_RELEASE",
  "PROD_DEPLOYED",
  "CLOSED",
  "INVALID",
  "REPORTED",
  "TRIAGED",
  "IN_PROGRESS",
  "FIXED",
  "VERIFIED",
  "REJECTED",
];

export const allowedTransitions: Record<IssueStatus, readonly IssueStatus[]> = {
  OPEN: [
    "READY_FOR_DEV",
    "DEV_IN_PROGRESS",
    "DEV_REVIEW",
    "DEV_COMPLETED",
    "DEV_DEPLOYED",
    "QA_IN_PROGRESS",
    "QA_DEPLOYED",
    "READY_FOR_RELEASE",
    "PROD_DEPLOYED",
    "CLOSED",
    "INVALID",
    "IN_PROGRESS",
    "FIXED",
    "REJECTED",
  ],
  READY_FOR_DEV: [
    "DEV_IN_PROGRESS",
    "DEV_REVIEW",
    "DEV_COMPLETED",
    "DEV_DEPLOYED",
    "QA_IN_PROGRESS",
    "QA_DEPLOYED",
    "READY_FOR_RELEASE",
    "PROD_DEPLOYED",
    "OPEN",
    "CLOSED",
    "INVALID",
    "REJECTED",
  ],
  DEV_IN_PROGRESS: [
    "DEV_REVIEW",
    "DEV_COMPLETED",
    "DEV_DEPLOYED",
    "QA_IN_PROGRESS",
    "QA_DEPLOYED",
    "READY_FOR_RELEASE",
    "PROD_DEPLOYED",
    "READY_FOR_DEV",
    "OPEN",
    "CLOSED",
    "INVALID",
    "REJECTED",
  ],
  DEV_REVIEW: [
    "DEV_COMPLETED",
    "DEV_IN_PROGRESS",
    "DEV_DEPLOYED",
    "QA_IN_PROGRESS",
    "QA_DEPLOYED",
    "READY_FOR_RELEASE",
    "PROD_DEPLOYED",
    "CLOSED",
    "INVALID",
    "READY_FOR_DEV",
    "OPEN",
    "REJECTED",
  ],
  DEV_COMPLETED: [
    "DEV_DEPLOYED",
    "QA_IN_PROGRESS",
    "QA_DEPLOYED",
    "READY_FOR_RELEASE",
    "PROD_DEPLOYED",
    "DEV_IN_PROGRESS",
    "DEV_REVIEW",
    "CLOSED",
    "INVALID",
    "OPEN",
    "REJECTED",
  ],
  DEV_DEPLOYED: [
    "QA_IN_PROGRESS",
    "QA_DEPLOYED",
    "READY_FOR_RELEASE",
    "PROD_DEPLOYED",
    "DEV_IN_PROGRESS",
    "DEV_COMPLETED",
    "CLOSED",
    "INVALID",
    "OPEN",
    "REJECTED",
  ],
  QA_IN_PROGRESS: [
    "QA_DEPLOYED",
    "READY_FOR_RELEASE",
    "PROD_DEPLOYED",
    "DEV_IN_PROGRESS",
    "READY_FOR_DEV",
    "DEV_COMPLETED",
    "CLOSED",
    "INVALID",
    "OPEN",
    "REJECTED",
  ],
  QA_DEPLOYED: [
    "READY_FOR_RELEASE",
    "PROD_DEPLOYED",
    "QA_IN_PROGRESS",
    "DEV_IN_PROGRESS",
    "CLOSED",
    "INVALID",
    "OPEN",
    "REJECTED",
  ],
  READY_FOR_RELEASE: [
    "PROD_DEPLOYED",
    "CLOSED",
    "QA_DEPLOYED",
    "DEV_IN_PROGRESS",
    "INVALID",
    "OPEN",
    "REJECTED",
  ],
  PROD_DEPLOYED: [
    "CLOSED",
    "OPEN",
    "DEV_IN_PROGRESS",
    "READY_FOR_DEV",
    "INVALID",
    "REJECTED",
  ],
  CLOSED: [
    "OPEN",
    "READY_FOR_DEV",
    "DEV_IN_PROGRESS",
    "IN_PROGRESS",
    "INVALID",
  ],
  INVALID: [
    "OPEN",
    "READY_FOR_DEV",
    "DEV_IN_PROGRESS",
    "CLOSED",
    "REJECTED",
  ],

  // Legacy mappings to preserve compatibility with existing database rows and tests
  REPORTED: [
    "IN_PROGRESS",
    "FIXED",
    "REJECTED",
    "TRIAGED",
    "OPEN",
    "READY_FOR_DEV",
    "DEV_IN_PROGRESS",
    "DEV_REVIEW",
    "DEV_COMPLETED",
    "DEV_DEPLOYED",
    "QA_IN_PROGRESS",
    "QA_DEPLOYED",
    "READY_FOR_RELEASE",
    "PROD_DEPLOYED",
    "CLOSED",
    "INVALID",
  ],
  TRIAGED: [
    "IN_PROGRESS",
    "FIXED",
    "REJECTED",
    "REPORTED",
    "READY_FOR_DEV",
    "DEV_IN_PROGRESS",
    "OPEN",
  ],
  IN_PROGRESS: [
    "FIXED",
    "REJECTED",
    "TRIAGED",
    "DEV_REVIEW",
    "DEV_COMPLETED",
    "DEV_DEPLOYED",
    "QA_IN_PROGRESS",
    "QA_DEPLOYED",
    "READY_FOR_RELEASE",
    "PROD_DEPLOYED",
  ],
  FIXED: [
    "IN_PROGRESS",
    "VERIFIED",
    "REJECTED",
    "CLOSED",
    "QA_DEPLOYED",
    "READY_FOR_RELEASE",
    "PROD_DEPLOYED",
  ],
  VERIFIED: [
    "CLOSED",
    "IN_PROGRESS",
    "REJECTED",
    "PROD_DEPLOYED",
  ],
  REJECTED: [
    "OPEN",
    "READY_FOR_DEV",
    "DEV_IN_PROGRESS",
    "IN_PROGRESS",
    "CLOSED",
    "INVALID",
  ],
};

export function canTransition(from: IssueStatus | string, to: IssueStatus | string): boolean {
  if (from === to) return false;
  const standardAllowed = (allowedTransitions as Record<string, readonly string[]>)[from];
  if (standardAllowed) {
    if (standardAllowed.includes(to)) return true;
    // If target is a custom status, allow transition from active states
    if (!(to in allowedTransitions)) {
      return from !== "CLOSED" && from !== "INVALID";
    }
    return false;
  }
  // If source is a custom status, allow transition to other statuses
  return true;
}
